openapi: 3.0.3
info:
  title: ''
  version: 1.0.0
  description: Building the FutuR
paths:
  /api/brands/:
    get:
      operationId: brands_list
      description: A simple ViewSet for viewing all brands.
      tags:
      - brands
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Brand'
          description: ''
  /api/categories/:
    get:
      operationId: categories_list
      description: A simple ViewSet for viewing all categories.
      tags:
      - categories
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Category'
          description: ''
  /api/products/:
    get:
      operationId: products_list
      description: A simple ViewSet for viewing all Products.
      tags:
      - products
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
          description: ''
  /api/products/{slug}/:
    get:
      operationId: products_retrieve
      description: A simple ViewSet for viewing all Products.
      parameters:
      - in: path
        name: slug
        schema:
          type: string
        required: true
      tags:
      - products
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
          description: ''
  /api/products/category/{category}/all/:
    get:
      operationId: products_category_all_retrieve
      description: An endpoint to return products by category.
      parameters:
      - in: path
        name: category
        schema:
          type: string
          pattern: ^\w+$
        required: true
      tags:
      - products
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
          description: ''
components:
  schemas:
    Brand:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 100
      required:
      - id
      - name
    Category:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 100
      required:
      - id
      - name
    Product:
      type: object
      properties:
        name:
          type: string
          maxLength: 100
        slug:
          type: string
          maxLength: 255
          pattern: ^[-a-zA-Z0-9_]+$
        description:
          type: string
        brand_name:
          type: string
        category_name:
          type: string
        product_line:
          type: array
          items:
            $ref: '#/components/schemas/ProductLine'
      required:
      - brand_name
      - category_name
      - name
      - product_line
      - slug
    ProductLine:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        price:
          type: string
          format: decimal
          pattern: ^-?\d{0,3}(?:\.\d{0,2})?$
        sku:
          type: string
          maxLength: 100
        stock_qty:
          type: integer
      required:
      - id
      - price
      - sku
      - stock_qty
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
