# Generated by Django 4.2.1 on 2023-06-24 17:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0005_alter_productline_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="slug",
            field=models.SlugField(default="pend", max_length=255),
            preserve_default=False,
        ),
    ]
