# Generated by Django 4.2.1 on 2023-11-13 02:19

from django.db import migrations
import ekommerz.product.fields


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0007_brand_is_active_category_is_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productline",
            name="order",
            field=ekommerz.product.fields.OrderField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
