# Generated by Django 4.2.1 on 2023-11-18 21:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0008_productline_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
